login/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as authviews
from . import views

app_name = 'login'

urlpatterns = [
    path('newuser/', views.register, name='register'),
    path('login/', authviews.LoginView.as_view(template_name='login/login.html'), name='login'),
    path('logout/', authviews.LogoutView.as_view(template_name='login/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('check_username/', views.check_username, name='check_username')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

tk2_e12/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('artikel/', include('artikel.urls')),
    path('', include('main.urls')),
    path('Form/', include('Formulir.urls'), name="Formulir"),
    path('', include('login.urls')),
]

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegister(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name','last_name','username', 'email', 'password1', 'password2']

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserRegister
from django.http import JsonResponse
from django.contrib.auth.models import User

def register(request):
    if request.method == 'POST':
        form = UserRegister(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Account Succesfully Registered')
            return redirect('/login/')
    else:    
        form = UserRegister()
    return render(request, 'login/register.html', {'form': form})

def check_username(request):
    username = request.GET.get('username', None)
    data = {
        'username_taken': User.objects.filter(username__iexact=username).exists()
    }
    return JsonResponse(data)

@login_required
def profile(request):
    return render(request, 'login/profile.html')

login/templates/login/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="container">
    <div class="login_form">
        <h1> LOG IN </h1>
        <div class="login_box">
            <div class="container">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <p>Belum Punya Akun ? <a class ="registhere" href="{% url 'login:register' %}">REGISTER HERE</a></p>
                <div class="button">
                    <button class="btn btn-outline-info" type="submit">Login</button>
                </div>
            </form>
        </div>
        </div>
    </div>
</div>
{% endblock content %}

login/templates/login/logout.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="logout_page">
        <h1> LOG OUT </h1>
        <p class="logout_bold">You Are Already Logged Out</p>
        <p class="clickhere">If you want to log in again<a class ="loginhere" href="{% url 'login:login' %}"> CLICK HERE</a></p>
    </div>
</div>
{% endblock content %}

login/templates/login/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="prof_page">
        <h1> {{user.username}}'s Profile </h1>
        <div class="prof_box">
            <div class="container">
                <p>First Name : {{ user.first_name }}</p>
                <p>Last Name : {{ user.last_name }} </p>
                <p>Email : {{ user.email }}</p>
                <a class ="logouthere" href="{% url 'login:logout' %}"> Log Out</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

login/templates/login/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block meta %}

{% endblock meta %}

{% block content %}
<div class="container">
    <div class="regist_form">
        <h1> REGISTER </h1>
        <div class="regist_box">
            <div class="container">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <p>* required field</p>
                <div class="button">
                    <button class="btn btn-outline-info" type="submit" id="submit_register">Sign Up</button>
                    <p id="reg_req"> Register Requirements </p>
                </div>
            </form>
        </div>
        </div>
    </div>
</div>

<script src="{% static 'login.js' %}"></script>
{% endblock content %}