artikel/urls.py
from django.urls import path
from . import views

app_name = 'artikel'

urlpatterns = [
    path('', views.artikel, name='index'),
    path('tulis', views.tulis, name='tulis'),
    path('detail/<slug:slug>/', views.show_artikel, name='show_artikel'),
    path('delete/<int:id>/', views.delete_comment, name='delete_comment'),
]

login/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as authviews
from . import views

app_name = 'login'

urlpatterns = [
    path('newuser/', views.register, name='register'),
    path('login/', authviews.LoginView.as_view(template_name='login/login.html'), name='login'),
    path('logout/', authviews.LogoutView.as_view(template_name='login/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('check_username/', views.check_username, name='check_username')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

tk2_e12/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('artikel/', include('artikel.urls')),
    path('', include('main.urls')),
    path('Form/', include('Formulir.urls'), name="Formulir"),
    path('', include('login.urls')),
]

artikel/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Artikel(models.Model):
    slug = models.SlugField()
    judul = models.CharField(max_length=150)
    isi = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE ,default=None)

    def save(self, *args, **kwargs):
        suffix = 0
        candidate = base = slugify(self.judul[:50])
        self.slug = None
        while not self.slug:
            if suffix:
                candidate = f'{base}-{suffix}'
            if not Artikel.objects.filter(slug=candidate).exists():
                self.slug = candidate
            suffix += 1
        super(Artikel, self).save(*args, **kwargs)

    def __str__(self):
        return self.judul

    def snippet(self):
        return self.isi[:150] + '...' if len(self.isi) > 150 else self.isi


class Comment(models.Model):
    artikel = models.ForeignKey(Artikel, on_delete=models.CASCADE ,default=None, related_name="artikel")
    author = models.ForeignKey(User, on_delete=models.CASCADE ,default=None, related_name="author")
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.body, self.author)

artikel/forms.py
from django import forms
from . import models

class TulisArtikel(forms.ModelForm):
    class Meta:
        model = models.Artikel
        fields = ['judul','isi']

    error_messages = {
        'required' : 'Please type'
    }

    judul_attrs = {
        'type' : 'text',
        'placeholder' : 'Judul artikel'
    }

    isi_attrs = {
        'type' : 'text',
        'placeholder' : 'Text artikel ...'
    }

    judul = forms.CharField(label='Judul artikel:', required=True, max_length=150, widget=forms.TextInput(attrs=judul_attrs))
    isi = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=isi_attrs))

class TulisComment(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['body']
    body_attrs = {
        'type' : 'text',
        'placeholder' : 'Write a comment on this article',
        'style' :'width: 100%;margin-bottom:10px;margin-right:20px;',
    }

    body = forms.CharField(label='', required=True, max_length=300, widget=forms.TextInput(attrs=body_attrs))

artikel/views.py
from django.shortcuts import render, redirect
from .models import Artikel
from . import forms
from django.contrib.auth.decorators import login_required
from artikel.forms import TulisComment
from django.core import serializers
from django.http import HttpResponse, JsonResponse
from artikel.models import Comment
import json

def artikel(request):
    liat_artikel = ''
    list_artikel = Artikel.objects.all()
    return render(request, 'artikel/index.html', {'list_artikel':list_artikel, 'liat_artikel':liat_artikel})

def show_artikel(request, slug):
    list_artikel = Artikel.objects.all()
    liat_artikel = Artikel.objects.get(slug=slug)
    list_comment = Comment.objects.filter(artikel=liat_artikel).order_by("-id")
    if request.method == "POST":
        form = TulisComment(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.artikel = liat_artikel
            comment.save()

            strJson = '[{"author":"%s","body":"%s","date":"%s","id":"%s"}]' %(comment.author.get_full_name(),comment.body,comment.date.strftime("%b. %d, %Y, %I:%M %p"), comment.id)
            responseData = json.loads(strJson)
            return JsonResponse(responseData, status=200, safe=False)
        else:
            return JsonResponse({"error":form.errors}, status=400)
    elif request.method == "GET":
        form = TulisComment()
        return render(request, 'artikel/index.html', {'list_artikel':list_artikel, 'liat_artikel':liat_artikel, 'form':form, 'list_comment':list_comment})
    else:
        return JsonResponse({"error":""}, status=400)


def delete_comment(request, id):
    comment = Comment.objects.get(id=id)
    comment.delete()
    return JsonResponse({"success":id}, safe=False)


@login_required(login_url='/login/')
def tulis(request):
    if request.method == 'POST':
        form = forms.TulisArtikel(request.POST)
        if form.is_valid():
            art = form.save(commit=False)
            art.author = request.user
            art.save()
            return redirect('artikel:index')
    else:
        form = forms.TulisArtikel()
    return render(request, 'artikel/tulis.html', {'form':form})

artikel/templates/artikel/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Artikel</title>
<script src="{% static 'js/script.js' %}"></script>
{% endblock meta %}

{% block content %}
<div class="container view_artikel">
    <a href="{% url 'artikel:tulis' %}"><button class="button-tulis-blog">Tulis Blogmu</button></a>
    <div class="row">
        <div class="blog col-8">
            {% if liat_artikel == '' %}
            <h1 class="hidden_h1">Ayo tulis artikelmu!</h1>
            {% else %}
            <h2 class="judul_artikel">{{ liat_artikel.judul }}</h2>
            <h5 class="author_artikel">Oleh: {{ liat_artikel.author.get_full_name }}</h5>
            <p class="isi_artikel">{{ liat_artikel.isi|linebreaks}}</p>
            {% endif %}
        </div>

        <div class="list_blog col-3">
            {% if list_artikel.count != 0 %}
            <h2 id="baca_artikel">Baca artikel lain</h2>
            {% for art in list_artikel %}
            <div class="blog-entry">
                <h6 class="list_judul"><a href="{% url 'artikel:show_artikel' slug=art.slug %}">{{ art.judul }}</a>
                </h6>
                <p class="list_snippet">{{ art.snippet }}</p>
            </div>
            {% endfor %}
            {% else %}
            <h5 class="hidden_h1">Belum ada artikel lain :(</h5>
            {% endif %}
        </div>
    </div>
    {% if liat_artikel == '' %}
    {% else %}
    <h2 class="comments-header">Comments</h2>
    <div class="row">
        <div class="comment-artikel-container col">
            {% if user.is_authenticated %}
            <p>Comment as {{request.user.get_full_name}} <a href="{% url 'login:logout' %}">• Logout</a></p>
            <form id="form-comment" action="." method="POST">
                {% csrf_token %}
                {{ form }}
                <input id="post_btn" type="submit" value="Post">
            </form>

            {% else %}
            <p><a href="{% url 'login:login' %}?next={{request.path}}">Login</a> to write a comment.</p>
            {% endif %}
            <div class="list-comment">
                {% for comment in list_comment %}
                <div class="comment-artikel col">
                    {% if request.user == comment.author %}
                    <button 
                        href="{% url 'artikel:delete_comment' comment.id %}" 
                        style="float: right;padding: 5px; margin-top: 5px;" 
                        type="button" 
                        class="del_btn btn btn-outline-danger">
                        x</button>
                    {% endif %}

                    <h4 style="display: inline-block;margin-top: 5px;">{{ comment.author.get_full_name }} •</h4>
                    <p style="display: inline-block;margin-left: 10px;">{{ comment.date }} </p>
                    <p>{{ comment.body }}</p>

                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock content %}

artikel/templates/artikel/tulis.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Tulis Artikel</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <h4 id="buat-blog">Buat Blog</h4>
    <form class="site-form" action="{% url 'artikel:tulis' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input id="submit_btn" type="submit" value="Submit">
    </form>
</div>
{% endblock content %}