Formulir/urls.py
from django.urls import path
from . import views

app_name = "Formulir"
urlpatterns = [
    path('', views.formPage, name="formulir"),
    path('listForm/', views.listForm, name="listForm"),
]

artikel/urls.py
from django.urls import path
from . import views

app_name = 'artikel'

urlpatterns = [
    path('', views.artikel, name='index'),
    path('tulis', views.tulis, name='tulis'),
    path('detail/<slug:slug>/', views.show_artikel, name='show_artikel'),
    path('delete/<int:id>/', views.delete_comment, name='delete_comment'),
]

landing/urls.py
from django.urls import path

from . import views

app_name = 'landing'

urlpatterns = [
    path('', views.home, name='home'),
    path('pollsudah', views.pollSudah, name='sudah'),
    path('pollbelum', views.pollBelum, name='belum'),
    path('hasilpoll', views.hasilPoll, name='hasilPoll'),
]

login/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as authviews
from . import views

app_name = 'login'

urlpatterns = [
    path('newuser/', views.register, name='register'),
    path('login/', authviews.LoginView.as_view(template_name='login/login.html'), name='login'),
    path('logout/', authviews.LogoutView.as_view(template_name='login/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('check_username/', views.check_username, name='check_username')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

tk2_e12/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('artikel/', include('artikel.urls')),
    path('', include('main.urls')),
    path('Form/', include('Formulir.urls'), name="Formulir"),
    path('', include('login.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/icon.png' %}" />

  <!-- Bootstrap & CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
  <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet'>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
  <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <div class="page-container">
  <div class="content-wrap">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="{% url 'landing:home' %}">
      <img class="brand" src="{% static 'img/DeCare.png' %}" width="130" alt="brand">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" href="{% url 'landing:home' %}">Home <span class="sr-only">(current)</span></a>
        <a class="nav-link" href="{% url 'Formulir:formulir' %}">Daftar Check-up</a>
        <a class="nav-link" href="#">Konsultasi</a>
        <a class="nav-link" href="{% url 'artikel:index' %}">Blog</a>
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'login:profile' %}">My Profile</a>
        {% else %}
        <a class="nav-link" href="{% url 'login:login' %}">Log In</a>
        {% endif %}
      </div>
    </div>
  </nav>
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
  {% block content %}
  {% endblock content %}
  </div>
  </div>
  
  {% include 'footer.html'%}
</body>
</html>